name: github_commons
description: shared components and models
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_svg: ^2.0.3
  equatable: ^2.0.5
  url_launcher: ^6.1.9
  json_annotation: ^4.7.0
  flutter_modular: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  modular_test: ^2.0.0
  mobx_codegen: ^2.1.1
  mockito: ^5.3.2
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/github_icon.svg

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/Product-Sans-Regular.ttf
        - asset: fonts/Product-Sans-Bold.ttf
          weight: 700
